``` sql
create table person(
    name varchar(50)
    );

insert into person values('Abdul');
insert into person values('akash');
insert into person values('Tom');
insert into person values('harry');
insert into person values('kITTY');

select * from person;

+-------+
| name  |
+-------+
| Abdul |
| akash |
| Tom   |
| harry |
| kITTY |
+-------+

Q. Write an SQL query to list the names which start with lower case letters.

Expected output:

+-------+
| name  |
+-------+
| akash |
| harry |
| kITTY |
+-------+
```

### **Solution-1:**
``` sql
select * from person
where ascii(substring(name,1,1)) = ascii(lower(substring(name,1,1)));
```

### **Solution-2:**
``` sql
select * from person
where ascii(name) between 97 and 122;
```

### **Solution-3:**
``` sql
select * from person
where REGEXP_LIKE(name, '^[a-z]','c');
```

---
REGEXP_LIKE() is a more powerful and standard-compliant function available in MySQL 8.0+ for regex matching.

#### ✅ **Syntax:**

```sql
REGEXP_LIKE(expression, pattern [, match_type])
```

| Parameter    | Description                               |
| ------------ | ----------------------------------------- |
| `expression` | The column or string to check             |
| `pattern`    | The regex pattern                         |
| `match_type` | (Optional) Controls case sensitivity etc. |


#### ✅ **Example — Match Strings That Start with a Lowercase Letter:**

```sql
SELECT *
FROM your_table
WHERE REGEXP_LIKE(your_column, '^[a-z]');
```


#### ✅ **Example — Match Both Uppercase & Lowercase (Case-Insensitive):**

``` sql
SELECT *
FROM your_table
WHERE REGEXP_LIKE(your_column, '^[a-z]', 'i');  -- 'i' for case-insensitive
```

#### ✅ **Key Advantages over REGEXP:**

| Feature             | `REGEXP`             | `REGEXP_LIKE()`                              |
| ------------------- | -------------------- | -------------------------------------------- |
| Case-sensitivity    | Depends on collation | Controlled via `match_type`                  |
| Standard Compliance | No                   | Yes (SQL-standard function)                  |
| Readability         | Moderate             | Better (clear function)                      |
| Portability         | Low                  | Higher (similar in Oracle, PostgreSQL, etc.) |


#### **Lowercase letters only**
```sql
SELECT * FROM test_table WHERE REGEXP_LIKE(col, '^[a-z]');
```

#### **Case-insensitive match (both uppercase and lowercase)**
``` sql
SELECT * FROM test_table WHERE REGEXP_LIKE(col, '^[a-z]', 'i');
```

#### ✅ **Common match_type Options:**

| Match Type | Meaning                   |
| ---------- | ------------------------- |
| 'i'        | Case-insensitive          |
| 'c'        | Case-sensitive            |
| 'm'        | Multi-line mode           |
| 'n'        | '.' doesn’t match newline |