# **3415. Find Products with Three Consecutive Digits **

**Table: Products**
``` sql
+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| product_id  | int     |
| name        | varchar |
+-------------+---------+
```
product_id is the unique key for this table.

Each row of this table contains the ID and name of a product.

Write a solution to find all products whose names contain a sequence of exactly three digits in a row. 

Return the result table ordered by product_id in ascending order.

The result format is in the following example.

 

**Example:**

**Input:**

**products table:**
``` sql
+-------------+--------------------+
| product_id  | name               |
+-------------+--------------------+
| 1           | ABC123XYZ          |
| 2           | A12B34C            |
| 3           | Product56789       |
| 4           | NoDigitsHere       |
| 5           | 789Product         |
| 6           | Item003Description |
| 7           | Product12X34       |
+-------------+--------------------+
```
**Output:**
``` sql
+-------------+--------------------+
| product_id  | name               |
+-------------+--------------------+
| 1           | ABC123XYZ          |
| 5           | 789Product         |
| 6           | Item003Description |
+-------------+--------------------+
```
**Explanation:**

Product 1: ABC123XYZ contains the digits 123.

Product 5: 789Product contains the digits 789.

Product 6: Item003Description contains 003, which is exactly three digits.
Note:

Results are ordered by product_id in ascending order.

Only products with exactly three consecutive digits in their names are included in the result.

**Solution-1:**
``` sql
select * from products
where regexp_like (name, '[0-9]{3}') and (NOT regexp_like (name, '[0-9]{4}'))
```

**Solution-2:**
``` sql
SELECT product_id , name 
FROM Products
WHERE name like '%[0-9][0-9][0-9]%' and name not like '%[0-9][0-9][0-9][0-9]%'
order by product_id
```

**Solution-3:**
``` sql
SELECT 
    product_id, 
    name
FROM 
    Products
WHERE 
    name REGEXP '[0-9]{3}' AND name NOT REGEXP '[0-9]{4,}'
ORDER BY 
    product_id ASC;
```