# **2118. Build the Equation**

**Table: Terms**
``` console
+-------------+------+
| Column Name | Type |
+-------------+------+
| power       | int  |
| factor      | int  |
+-------------+------+
```
power is the column with unique values for this table.

Each row of this table contains information about one term of the equation.

power is an integer in the range [0, 100].

factor is an integer in the range [-100, 100] and cannot be zero.
 

You have a very powerful program that can solve any equation of one variable in the world. The equation passed to the program must be formatted as follows:

The left-hand side (LHS) should contain all the terms.

The right-hand side (RHS) should be zero.

Each term of the LHS should follow the format "<sign><fact>X^<pow>" where:

<sign> is either "+" or "-".

<fact> is the absolute value of the factor.

<pow> is the value of the power.

If the power is 1, do not add "^<pow>".

For example, if power = 1 and factor = 3, the term will be "+3X".

If the power is 0, add neither "X" nor "^<pow>".

For example, if power = 0 and factor = -3, the term will be "-3".

The powers in the LHS should be sorted in descending order.

Write a solution to build the equation.

The result format is in the following example.

 

**Example 1:**

**Input:** 
**Terms table:**
``` console
+-------+--------+
| power | factor |
+-------+--------+
| 2     | 1      |
| 1     | -4     |
| 0     | 2      |
+-------+--------+
```
**Output:**
``` console 
+--------------+
| equation     |
+--------------+
| +1X^2-4X+2=0 |
+--------------+
```
**Example 2:**

**Input:** 
**Terms table:**
``` console
+-------+--------+
| power | factor |
+-------+--------+
| 4     | -4     |
| 2     | 1      |
| 1     | -1     |
+-------+--------+
```
**Output:** 
``` console
+-----------------+
| equation        |
+-----------------+
| -4X^4+1X^2-1X=0 |
+-----------------+
 ```

Follow up: What will be changed in your solution if the power is not a primary key but each power should be unique in the answer?

**Solution-1:**

``` sql
# Write your MySQL query statement below

WITH CTE AS(SELECT  power,
CONCAT(CASE WHEN SUBSTRING(factor,1,1) = '-' THEN factor
ELSE CONCAT('+',factor) END,
CASE WHEN power NOT IN (1,0) THEN CONCAT('X^', power)
WHEN power = 1 THEN 'X'
ELSE '' END) AS eq
FROM Terms
WHERE (power BETWEEN 0 AND 100) 
AND((factor Between 1 AND 100) OR (factor Between -100 AND -1)) 
ORDER BY power DESC)

SELECT CONCAT(GROUP_CONCAT(eq ORDER BY power DESC SEPARATOR ''),'=0') as equation
FROM CTE

**Solution-2:**

``` sql
WITH eqn_reps AS (
  SELECT
    T.power,
    CONCAT( (CASE WHEN T.factor > 0 THEN '+' ELSE '-' END),
          (CASE
              WHEN T.power > 1 THEN CONCAT(ABS(T.factor), 'X^', T.power)
              WHEN T.power = 1 THEN CONCAT(ABS(T.factor), 'X')
              ELSE ABS(T.factor) END)
          ) AS eqn_rep
  FROM Terms T
)
SELECT
  CONCAT(GROUP_CONCAT(E.eqn_rep ORDER BY E.power DESC SEPARATOR ''), '=0') AS equation
FROM
  eqn_reps E;